runtime: python39

env_variables:
  BOT_TOKEN: "8402864290:AAH_oGrMj-gyVnC4Ss2ax0lDkzGO7DZ_ykE"
  CHAT_ID: "44705783"

handlers:
- url: /etf-report
  script: auto
  secure: always
  
- url: /.*
  script: auto

# 자동 스케일링 설정
automatic_scaling:
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 10
